name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3
      - name: Use Bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Lint files
        run: bun run lint
