name: Tests
on:
  push:
    branches:
      - main
  pull_request:
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout commit
        uses: actions/checkout@v4
      - name: Use Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.0
      - name: Install dependencies
        run: bun install
      - name: Run linting
        run: bun run lint
      - name: Run tests
        run: bun run test
